### PR TITLE
Add Comix-Harem support

### PR DESCRIPTION
**Pull request by bohammettuz**
I've long wanted to have the Harem++ features available in Comix Harem.
I'm new to front-end development, but this update seems to do a good job in my local testing on both HH and CxH.

CxH has a few hair and eye colors that aren't in HH, but the overlap is large enough that I didn't think it worth splitting that apart per game.
Pose data has some re-used girl ids that have different poses in each game, so that did need to be separated.

### CODE REVIEW

**Comment by rena-jp** [comment]
Thank you so much! I have merged it. I will also post it on the forum.

**Comment by rena-jp** [comment]
I just noticed that you sent a pull request using an account named bohammettuz but the code had been committed by a different account. If you made a mistake, please send a pull request that was fixed. I will redo the merge.

**Comment by bohammettuz** [comment]
> I just noticed that you sent a pull request using an account named bohammettuz but the code had been committed by a different account. If you made a mistake, please send a pull request that was fixed. I will redo the merge.

Thanks for noticing that. I was trying to keep this separated from my main github activity. There's always somewhere you slip up when trying to be sneaky. :-)
I just made a new PR with the author/committer fixed.

**Comment by bohammettuz** [comment]
Perhaps as a final cleanup of the committer mistake, you could delete this first PR completely?

**Comment by rena-jp** [comment]
Sorry, but my account does not allow me to remove it. I have just asked GitHub Support to remove it.

**Pull request merged**
